addons:
  apt:
    packages:
    - oracle-java8-installer
after_success:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.host.url=https://sonarcloud.io
  -Dsonar.login=$SONAR_TOKEN
- bash update-ghpages.sh
before_cache:
- rm -rf $HOME/CACHE; find $TRAVIS_BUILD_DIR -name .ekstazi | while read line; do
  du -sh $line;         DIR=$(dirname $HOME/CACHE$line); mkdir -p $DIR; cp -r $line
  $DIR; done
- echo CACHESIZE $(du -sk $HOME/CACHE)
before_install:
- find $HOME/CACHE -name .ekstazi | while read line; do du -sh $line;         DIR=$(dirname
  ${line#$HOME/CACHE}); if [[ -d ${DIR#.ekstazi/} ]]; then cp -r $line $DIR; fi; done
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- find $TRAVIS_BUILD_DIR -name .ekstazi | while read line; do rm -rf $line; done;find
  $HOME/CACHE -name .ekstazi | while read line; do du -sh $line;         DIR=$(dirname
  ${line#$HOME/CACHE}); if [[ -d ${DIR#.ekstazi/} ]]; then cp -r $line $DIR; fi; done
cache:
  directories:
  - $HOME/CACHE
env:
  global:
  - GH_REF: github.com/iluwatar/java-design-patterns.git
  - secure: LxTDuNS/rBWIvKkaEqr79ImZAe48mCdoYCF41coxNXgNoippo4GIBArknqtv+XvdkiuRZ1yGyj6pn8GU33c/yn+krddTUkVCwTbVatbalW5jhQjDbHYym/JcxaK9ZS/3JTeGcWrBgiPqHEEDhCf26vPZsXoMSeVCEORVKTp1BSg=
  - secure: eoWlW9GyTJY04P8K3pxayXwU9/hmptQg/LfirispQkV9YvmziCfSzXnatnBhNfud98sCzY8BScXnb+OWLTnjLKpId4rtEqb0aJ40Jc32cUKzgzFAUn7cNcDAbUIfyPAGVqyQqfj/11wYSADwWMMOPlW97ExUtoyiH2WenXuRHso=
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -e
jdk:
- oraclejdk8
language: java
script:
- touch /tmp/NOW;echo SCRIPT_START $(date)
- mvn test -B
- echo SCRIPT_END $(date);echo TESTNUM $(grep -l "<testcase" $(find $TRAVIS_BUILD_DIR
  -name TEST-*.xml -newer /tmp/NOW | wc -l))
sudo: required
